In [2]:
import torch
import numpy as np

# Numpy Array

In [4]:
np1 = np.random.randn(3, 5)

np1

array([[-0.61176524, -0.0081036 ,  0.49056063,  1.50532602,  0.24205477],
       [-1.32411947,  0.96568141,  0.48193595,  0.1151896 , -1.63012223],
       [-0.877762  , -0.90637092, -0.73445196, -0.81771459, -0.37223259]])

# Tensorflow

In [5]:
tensor_2d = torch.randn(3, 5)

In [6]:
tensor_2d

tensor([[-0.8680,  0.4546, -1.2789, -0.4975,  1.6441],
        [ 0.0415,  0.3659, -0.0604, -1.2046,  0.2959],
        [-1.0311, -0.4381, -1.2786,  1.6720, -0.8976]])

In [9]:
torch.device


torch.device

In [10]:
my_torch = torch.arange(10)
my_torch


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# SMALL NN

In [12]:
import torch.nn as nn 
import torch.nn.functional as F

In [13]:
# Create a Model CLass that inherits from nn.Module
class Model(nn.Module):
    # 4 valuea in inpurt, 1 output
    def __init__(self, n_input=4, h1=8, h2=9,n_output=3):
        super(Model,self).__init__()

        self.fc1 = nn.Linear(n_input, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, n_output)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.out(x)

        return x 
    
    
    
        
        

In [14]:
torch.manual_seed(41)

#create a model instance
model = Model()